const translations={
ru:{
navEarn:'Как зарабатывать',navSupport:'Что мы даём',navStart:'Как начать',navApply:'Хочу в агентство',
heroTitle:'Начни <em>зарабатывать онлайн</em> на прямых эфирах',heroLead:'Общайся с людьми в прямом эфире, развивай свою аудиторию и получай доход от контента. Даже если ты никогда раньше не стримила — ABHIGREEN поможет начать с нуля.',heroCta:'Хочу попробовать',heroSecond:'Как устроен заработок?',joinBonusTitle:'$15 бонус при подключении',joinBonusText:'Для новых подходящих стримеров ABHIGREEN • условия подтверждает менеджер',connectionBonusTitle:'Бонус за подключение: $15',connectionBonusText:'для подходящих новых стримеров после подключения к ABHIGREEN',
trust1a:'Без опыта',trust1b:'обучим с нуля',trust2a:'Гибкий формат',trust2b:'стримишь удалённо',trust3a:'Личный менеджер',trust3b:'не остаёшься одна',
visualToday:'Сегодня',visualEarn:'Монетизация',visualEarn2:'Подарки → внутренняя валюта',visualManager:'Менеджер рядом',
quick1a:'Можно начать с телефона',quick1b:'без сложной техники',quick2a:'Работай удалённо',quick2b:'из удобного тебе места',quick3a:'Не нужно быть блогером',quick3b:'важнее общение и регулярность',quick4a:'Поддержка агентства',quick4b:'от профиля до роста аудитории',
introTitle:'Это не «сидеть в интернете».<br><em>Это работа с аудиторией.</em>',introText:'Ты выходишь в эфир, общаешься, знакомишься с людьми, создаёшь настроение и постепенно собираешь вокруг себя постоянных зрителей. Чем сильнее твоя аудитория и активнее эфиры — тем больше возможностей для монетизации.',introNote:'Доход не гарантирован: он зависит от активности, аудитории, формата контента, региона и актуальных правил Tango.',
earnTitle:'Откуда вообще берётся <em>заработок?</em>',earnSub:'На Tango есть несколько способов монетизировать активность и внимание аудитории. Мы помогаем понять, как использовать их грамотно.',
money1t:'Подарки во время эфиров',money1p:'Зрители могут отправлять виртуальные подарки. По актуальным правилам Tango они учитываются в системе платформы и могут участвовать в механике выплат.',money2t:'Лояльная аудитория',money2p:'Постоянные зрители возвращаются на эфиры, участвуют в общении и поддерживают стримеров, которые им нравятся. Мы учим не просто «сидеть в кадре», а строить сообщество.',money3t:'Батлы и активности',money3p:'Батлы, цели и события делают эфир динамичнее и могут давать дополнительные возможности для монетизации и бонусов по текущим условиям платформы.',money4t:'Платный контент',money4p:'Tango развивает платный контент и другие форматы, поэтому профиль может давать дополнительные возможности для монетизации и вне прямого эфира.',moneySummary:'<b>Главное:</b> тебе не нужно приходить с огромной аудиторией. Нужны желание общаться, регулярность и готовность учиться — всё остальное мы разберём вместе.',
supportTitle:'Ты не просто получаешь код.<br><em>Ты получаешь команду.</em>',supportLead:'Наша задача — сократить путь новичка от «я вообще не понимаю, что делать» до уверенных, регулярных эфиров.',s1t:'Настройка профиля',s1p:'Поможем с оформлением, позиционированием и первым впечатлением для зрителей.',s2t:'Подготовка к первым эфирам',s2p:'Разберём свет, кадр, темы, формат общения и как не зависнуть в тишине.',s3t:'Обучение монетизации',s3p:'Объясним механику подарков, активности зрителей и способы развивать постоянную аудиторию.',s4t:'Контент и идеи',s4p:'Подскажем темы, форматы, цели и активности, чтобы эфиры не превращались в одно и то же.',s5t:'Правила Tango',s5p:'Поможем понять, что можно и нельзя, чтобы работать безопасно и не рисковать аккаунтом.',s6t:'Личный менеджер',s6p:'Можно задавать вопросы, разбирать сложные ситуации и корректировать стратегию по мере роста.',
codeTitle:'Подключиться к ABHIGREEN в Tango можно двумя способами',codeText:'Выбери способ для своего телефона. Если что-то не получается — менеджер поможет.',androidTitle:'Самый быстрый способ',androidText:'На Android реферальная ссылка открывает Tango и помогает начать подключение.',openTango:'Нажми здесь, чтобы присоединиться',androidNote:'Реферальная ссылка предназначена для Android.',iosTitle:'Создай аккаунт через сайт Tango',iosText:'На iPhone открой tango.me, создай новый аккаунт, затем в Tango зайди в Settings → Join an Agency и введи код ABHIGREEN.',openTangoWeb:'Открыть tango.me',iosNote:'Для нового аккаунта используй код в первые 5 часов.',codeLabel:'TANGO AGENCY CODE',copyCode:'Скопировать код',copied:'Скопировано ✓',codeWarning:'Этот код вводится в Tango, не на сайте.',guideTitle:'Инструкция: как подключиться к ABHIGREEN',guideText:'Шаги теперь собраны прямо на странице — текст остаётся чётким на любом экране и не превращается в пиксели.',guideQuality:'Не скриншот: это живая веб-инструкция в высоком качестве.',guideCodeNote:'Код вводится внутри Tango, не на сайте.',guideAndroid1:'Нажми на реферальную ссылку',guideAndroid2:'Открой Tango и создай аккаунт',guideAndroid3:'Заверши подключение к агентству',guideIos1:'Открой tango.me',guideIos2:'Создай новый аккаунт',guideIos3:'В Tango: Settings → Join an Agency',guideIos4:'Введи KCu4ZY в первые 5 часов',guideBonusTitle:'Бонус $15',guideBonusText:'Для подходящих новых стримеров • условия подтверждает менеджер',openGuide:'Открыть инструкцию крупно',
fitTitle:'Подойдёт, если ты хочешь <em>новый онлайн-формат работы</em>',fit1:'Тебе 18 лет или больше',fit2:'Тебе комфортно общаться с людьми',fit3:'Готова появляться в кадре и быть собой',fit4:'Хочешь гибкий удалённый формат',fit5:'Готова выходить в эфир регулярно',fit6:'Хочешь учиться и развивать аудиторию',rulesNote:'Мы работаем только с реальными стримерами. Записанные трансляции, фейковые аккаунты, выдача себя за другого человека и обход правил платформы не допускаются.',
faqTitle:'Вопросы перед стартом',applyTitle:'Хочешь попробовать?<br><em>Напиши нам.</em>',applyLead:'Оставь короткую заявку. Мы посмотрим, подойдёт ли тебе формат, ответим на вопросы и объясним следующие шаги без давления.',remote:'Удалённо',fName:'Как тебя зовут?',fCountry:'Страна',fExperience:'Есть опыт стримов?',fTango:'Если уже есть Tango — username',fHours:'Сколько времени в неделю готова уделять?',fMessage:'Расскажи пару слов о себе',age:'Мне 18 лет или больше.',consent:'Я согласна с политикой конфиденциальности и условиями использования.',send:'Отправить заявку',footerText:'Помогаем девушкам 18+ уверенно начать и развиваться в прямых эфирах.'
},
en:{
navEarn:'How you earn',navSupport:'Our support',navStart:'How to start',navApply:'Join the agency',
heroTitle:'Start <em>earning online</em> with live streaming',heroLead:'Meet people live, grow an audience and monetize your content. Even if you have never streamed before, ABHIGREEN helps you start from zero.',heroCta:'I want to try',heroSecond:'How does earning work?',joinBonusTitle:'$15 joining bonus',joinBonusText:'For eligible new ABHIGREEN creators • final conditions confirmed by your manager',connectionBonusTitle:'Welcome bonus: $15',connectionBonusText:'for eligible new creators after connecting to ABHIGREEN',
trust1a:'No experience needed',trust1b:'we teach beginners',trust2a:'Flexible format',trust2b:'stream remotely',trust3a:'Personal manager',trust3b:'support when you need it',
visualToday:'Today',visualEarn:'Monetization',visualEarn2:'Gifts → diamonds',visualManager:'Manager by your side',
quick1a:'Start with your phone',quick1b:'no complex setup',quick2a:'Work remotely',quick2b:'from a place that suits you',quick3a:'No influencer status needed',quick3b:'conversation matters more',quick4a:'Agency support',quick4b:'from profile to audience growth',
introTitle:'It is more than being online.<br><em>It is building an audience.</em>',introText:'You go live, talk, meet people, create a good atmosphere and gradually build a group of regular viewers. The stronger your audience and the more consistent your streams, the more monetization opportunities you can create.',introNote:'Earnings are not guaranteed and depend on creator activity, audience engagement, content, region and current Tango rules.',
earnTitle:'So where can <em>earnings</em> come from?',earnSub:'Tango offers several ways to monetize attention and engagement. We help you understand how to use them well.',
money1t:'Gifts during live streams',money1p:'Viewers send virtual gifts. They become diamonds in the creator account, which can be redeemed for real money under Tango’s current rules.',money2t:'A loyal audience',money2p:'Regular viewers return, participate and support creators they enjoy. We teach you to build a community instead of simply sitting on camera.',money3t:'Battles & activities',money3p:'Battles, goals and events make streams more dynamic and may create additional diamond and bonus opportunities under current platform conditions.',money4t:'Paid content',money4p:'Tango is expanding paid posts and other formats, so your profile can have monetization opportunities outside the exact moment you are live.',moneySummary:'<b>The key point:</b> you do not need to arrive with a huge audience. Bring your willingness to communicate, consistency and readiness to learn — we help with the rest.',
supportTitle:'You do not just get a code.<br><em>You get a team.</em>',supportLead:'Our job is to shorten the path from “I have no idea what to do” to confident, consistent live streams.',s1t:'Profile setup',s1p:'We help with positioning, presentation and the first impression viewers get.',s2t:'First-stream preparation',s2p:'We cover lighting, framing, topics, conversation flow and how to avoid awkward silence.',s3t:'Monetization coaching',s3p:'We explain gifts, viewer activity and ways to build a returning audience.',s4t:'Content ideas',s4p:'Get ideas for topics, formats, goals and activities so streams stay fresh.',s5t:'Tango rules',s5p:'We help you understand what is allowed so you can stream safely and protect your account.',s6t:'Personal manager',s6p:'Ask questions, discuss difficult situations and adjust your approach as you grow.',
codeTitle:'There are two ways to connect to ABHIGREEN in Tango',codeText:'Choose the option for your phone. Your manager can help if you get stuck.',androidTitle:'Fastest option',androidText:'On Android, the referral link opens Tango and helps start the connection process.',openTango:'Click here to join now',androidNote:'The referral link is intended for Android.',iosTitle:'Create your account through the Tango website',iosText:'On iPhone, open tango.me and create a new account. Then in Tango go to Settings → Join an Agency and enter the ABHIGREEN code.',openTangoWeb:'Open tango.me',iosNote:'For a new account, use the code within the first 5 hours.',codeLabel:'TANGO AGENCY CODE',copyCode:'Copy code',copied:'Copied ✓',codeWarning:'Enter this code inside Tango, not on this website.',guideTitle:'How to join ABHIGREEN on Tango',guideText:'The steps now live directly on the page, so the text stays sharp on every screen instead of turning into pixels.',guideQuality:'Not a screenshot: this is a live high-resolution web guide.',guideCodeNote:'Enter the code inside Tango, not on this website.',guideAndroid1:'Open the referral link',guideAndroid2:'Open Tango and create your account',guideAndroid3:'Finish connecting to the agency',guideIos1:'Open tango.me',guideIos2:'Create a new account',guideIos3:'In Tango: Settings → Join an Agency',guideIos4:'Enter KCu4ZY within the first 5 hours',guideBonusTitle:'$15 bonus',guideBonusText:'For eligible new creators • conditions confirmed by your manager',openGuide:'Open full-size guide',
fitTitle:'A fit if you want <em>a new remote way to work</em>',fit1:'You are 18 or older',fit2:'You enjoy talking to people',fit3:'You are comfortable appearing on camera as yourself',fit4:'You want a flexible remote format',fit5:'You can stream consistently',fit6:'You want to learn and grow an audience',rulesNote:'We work with real broadcasters only. Prerecorded streams, fake accounts, impersonation and attempts to bypass platform rules are not accepted.',
faqTitle:'Questions before you start',applyTitle:'Want to try?<br><em>Talk to us.</em>',applyLead:'Send a short application. We will help you understand whether the format fits you, answer your questions and explain next steps without pressure.',remote:'Remote',fName:'Your name',fCountry:'Country',fExperience:'Any streaming experience?',fTango:'If you already use Tango — username',fHours:'How much time can you stream each week?',fMessage:'Tell us a little about yourself',age:'I am 18 or older.',consent:'I agree to the Privacy Policy and Terms.',send:'Send application',footerText:'Helping women 18+ start and grow confidently in live streaming.'
}};
const faqs={
ru:[
['Мне обязательно уже быть блогером?','Нет. Для старта важнее уметь или хотеть общаться, быть естественной в кадре и регулярно выходить в эфир. Мы поможем с оформлением, темами и первыми шагами.'],
['Как именно зарабатывает стример?','Один из механизмов Tango — виртуальные подарки от зрителей. Также платформа развивает платный контент, батлы и другие активности. Конкретные условия выплат определяются актуальными правилами Tango.'],
['Сколько я смогу зарабатывать?','Фиксированной суммы нет и обещать её было бы неправильно. Результат зависит от времени в эфире, качества общения, постоянной аудитории, активности и правил платформы. Наша задача — помочь тебе быстрее разобраться и не терять время на типичных ошибках.'],
['Нужно ли платить ABHIGREEN за вступление?','За подачу заявки и вступление на сайте мы не берём оплату. Если появятся отдельные условия конкретной кампании, менеджер объяснит их заранее.'],
['Что мне понадобится для старта?','Смартфон, стабильный интернет, аккуратный кадр, желание общаться и время на регулярные эфиры. С остальной подготовкой поможем.'],
['Можно ли совмещать со своей работой или учёбой?','Формат стриминга гибкий, поэтому многие выстраивают расписание под свою жизнь. Но для роста важна регулярность.'],
['Что такое KCu4ZY?','Это код ABHIGREEN для подключения аккаунта именно внутри Tango. На сайте его вводить не нужно. Пошаговая инструкция есть выше на этой странице.'],
['Если у меня уже есть аккаунт Tango?','Укажи username в заявке и обязательно сообщи менеджеру, если аккаунт уже связан с другим агентством. Дальнейшие шаги зависят от правил платформы.'],
['Вы помогаете с идеями для эфиров?','Да. Мы можем разбирать темы, подачу, общение со зрителями, цели эфира и способы сделать контент живее.'],
['Есть ли правила по контенту?','Да. Tango устанавливает правила для live-контента, и их нужно соблюдать. Мы помогаем новичкам понять основные требования до старта.']
],
en:[
['Do I already need to be an influencer?','No. For beginners, being willing to communicate, appearing naturally on camera and streaming consistently matters more. We help with profile setup, topics and first steps.'],
['How does a streamer earn?','One of Tango’s core mechanisms is virtual gifts from viewers, which become diamonds in the creator account. Tango also supports paid content, battles and other monetization activities.'],
['How much can I earn?','There is no fixed amount and it would be misleading to promise one. Results depend on live hours, audience engagement, consistency, content and platform rules. Our role is to help you learn faster and avoid common beginner mistakes.'],
['Is there a fee to join ABHIGREEN?','We do not charge a website application or joining fee. If a specific campaign ever has separate conditions, your manager will explain them in advance.'],
['What do I need to start?','A smartphone, stable internet, a clean camera setup, willingness to communicate and time for consistent streams. We help with the rest of the preparation.'],
['Can I combine this with work or study?','Live streaming can be flexible, so many creators build a schedule around their life. Consistency still matters for growth.'],
['What is KCu4ZY?','It is the ABHIGREEN code used inside Tango to connect a broadcaster account to the agency. You do not enter it on this website.'],
['What if I already have a Tango account?','Add your username to the application and tell your manager if the account is already linked to another agency. Next steps depend on platform rules.'],
['Do you help with stream ideas?','Yes. We can work on topics, presentation, viewer conversations, stream goals and ways to make your content more engaging.'],
['Are there content rules?','Yes. Tango has live broadcasting rules that creators must follow. We help beginners understand the main requirements before they start.']
]};
let lang=localStorage.getItem('abhi_lang')||'ru';
const params=new URLSearchParams(location.search);const referralCode=(params.get('ref')||params.get('referral')||'').trim().slice(0,80);
const langButton=document.getElementById('langButton');
const menuButton=document.getElementById('menuButton');
const mobileMenu=document.getElementById('mobileMenu');
function applyLanguage(){
 document.documentElement.lang=lang;langButton.textContent=lang.toUpperCase();langButton.setAttribute('aria-label',lang==='ru'?'Switch to English':'Переключить на русский');
 document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});
 document.querySelectorAll('[data-i18n-html]').forEach(el=>{const k=el.dataset.i18nHtml;if(translations[lang][k])el.innerHTML=translations[lang][k]});
 const summary=document.querySelector('[data-i18n="moneySummary"]');if(summary)summary.innerHTML=translations[lang].moneySummary;
 renderFaq();localStorage.setItem('abhi_lang',lang);
}
function renderFaq(){
 const el=document.getElementById('faqList');el.innerHTML=faqs[lang].map((x,i)=>'<div class="faq-item '+(i===0?'open':'')+'"><button class="faq-q" type="button" aria-expanded="'+(i===0?'true':'false')+'"><span>'+x[0]+'</span><span>＋</span></button><div class="faq-a">'+x[1]+'</div></div>').join('');
 el.querySelectorAll('.faq-q').forEach(b=>b.addEventListener('click',()=>{const item=b.parentElement;item.classList.toggle('open');b.setAttribute('aria-expanded',item.classList.contains('open')?'true':'false')}));
}
langButton.addEventListener('click',()=>{lang=lang==='ru'?'en':'ru';applyLanguage()});
menuButton.addEventListener('click',()=>{mobileMenu.classList.toggle('hidden');menuButton.setAttribute('aria-expanded',mobileMenu.classList.contains('hidden')?'false':'true')});
mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.add('hidden');menuButton.setAttribute('aria-expanded','false')}));
const copyButton=document.getElementById('copyTangoCode');
copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText('KCu4ZY');copyButton.textContent=translations[lang].copied;setTimeout(()=>copyButton.textContent=translations[lang].copyCode,1600)}catch{copyButton.textContent='KCu4ZY'}});
document.getElementById('applicationForm').addEventListener('submit',async e=>{
 e.preventDefault();
 const form=e.currentTarget,fd=new FormData(form),result=document.getElementById('formResult'),submit=form.querySelector('button[type="submit"]');
 const hasContact=['telegram','whatsapp','instagram'].some(k=>String(fd.get(k)||'').trim());
 result.innerHTML='';
 if(!hasContact){result.innerHTML='<div class="form-error">'+(lang==='ru'?'Укажи хотя бы Telegram или WhatsApp, чтобы менеджер мог с тобой связаться.':'Add Telegram or WhatsApp so a manager can contact you.')+'</div>';return}
 const app=Object.fromEntries(fd.entries());
 app.age_confirmed=fd.get('age_confirmed')==='on';app.consent=fd.get('consent')==='on';app.referral_code=referralCode;app.source=location.href.split('#')[0];
 submit.disabled=true;
 try{
   const res=await fetch('./api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(app)});
   if(!res.ok){
     const localDemo=['localhost','127.0.0.1'].includes(location.hostname);
     if(localDemo){
       app.id=crypto.randomUUID?crypto.randomUUID():String(Date.now());app.created_at=new Date().toISOString();app.status='New';
       const saved=JSON.parse(localStorage.getItem('abhi_demo_applications')||'[]');saved.unshift(app);localStorage.setItem('abhi_demo_applications',JSON.stringify(saved));
       result.innerHTML='<div class="form-success">'+(lang==='ru'?'Демо-заявка сохранена только в этом браузере.':'Demo application saved in this browser only.')+'</div>';
     }else{throw new Error('SUBMISSION_FAILED')}
   }else{
     result.innerHTML='<div class="form-success">'+(lang==='ru'?'Спасибо! Заявка отправлена менеджеру.':'Thank you! Your application has been sent to the manager.')+'</div>';
   }
   form.reset();
 }catch{
   result.innerHTML='<div class="form-error">'+(lang==='ru'?'Не удалось отправить заявку. Эта версия сайта не передаёт данные менеджеру без подключённого backend. Используй способы подключения к Tango выше или открой рабочую production-версию сайта.':'We could not send the application. This site version cannot deliver leads without a connected backend. Use the Tango connection options above or open the production deployment.')+'</div>';
 }finally{submit.disabled=false}
});
applyLanguage();